 
% DRONE THERMAL SIMULATION - THREE MATERIALS
%
% Assumptions:
%   - Drone is thermally isotropic.
%   - Convection and radiation can be independently enabled/disabled below.
%   - Heat transfer is by conduction within the drone, laser heating,
%     and optionally convection/radiation at the external boundary.
%   - Each material/frequency case runs until either:
%         1) 60 seconds have elapsed, OR
%         2) the maximum nodal temperature reaches the material threshold at which point a phase change beings
%
% Materials:
%   PLA
%   Carbon-Carbon
%   Aluminum 6061-T6


clear;
clc;
close all;

%% USER CONTROLS
STEP_FILE = "Skydio_x10_model.step"; % relative pathway

% HEAT-LOSS TOGGLES
% Set either value to true/false to independently enable or disable
% convection and radiation in the thermal boundary condition.

USE_CONVECTION = true;
USE_RADIATION   = true;


rotation_frequencies = [0 .1 .2 .3 .4 .5 .6 .7 .8 .9 1];
nFreq = numel(rotation_frequencies);

% Maximum life / simulation time
% A case terminates when currentTime >= t_final.
t_final = 60.0;                         % [s]

dt = 0.01;                              % [s]

% Initial temperature
T0 = 293.15;                            % [K] = 20 degC
Tinf = 293.15;                          % [K] ambient air temperature

% FEM mesh size
meshSize = 0.05;                       % [m]

% MATERIAL DEFINITIONS

% PLA
PLA.rho = 1240;                         % kg/m^3
PLA.cp = 1800;                          % J/(kg*K)
PLA.k = 0.13;                           % W/(m*K)
PLA.emissivity = 0.90;                  % -
PLA.absorptivity = 0.80;                % -
PLA.melting = 423.15;                   % K

% Carbon reinforced carbon / carbon-carbon
Carbon.rho = 1590;                      % kg/m^3
Carbon.cp = 674;                        % J/(kg*K)
Carbon.k = 1.4;                         % W/(m*K), isotropic assumption
Carbon.emissivity = 0.78;               % -
Carbon.absorptivity = 0.80;             % -
Carbon.melting = 2030;                  % K, NASA single-use limit

% Aluminum 6061-T6
Al.rho = 2707;                          % kg/m^3
Al.cp = 896;                            % J/(kg*K)
Al.k = 170;                             % W/(m*K), isotropic assumption
Al.emissivity = 0.09;                   % -
Al.absorptivity = 0.80;                 % -
Al.melting = 867;                       % K

% Put all materials into one array for the outer material loop.
materials = struct(...
    "name", {"PLA", "Carbon", "Aluminum6061T6"}, ...
    "displayName", {"PLA", "Carbon-Carbon", "Aluminum 6061-T6"}, ...
    "rho", {PLA.rho, Carbon.rho, Al.rho}, ...
    "cp", {PLA.cp, Carbon.cp, Al.cp}, ...
    "k", {PLA.k, Carbon.k, Al.k}, ...
    "emissivity", {PLA.emissivity, Carbon.emissivity, Al.emissivity}, ...
    "absorptivity", {PLA.absorptivity, Carbon.absorptivity, Al.absorptivity}, ...
    "melting", {PLA.melting, Carbon.melting, Al.melting});

nMaterials = numel(materials);

%% OUTPUT FOLDER
outputFolder = "thermal_results_" + heatLossMode;

if USE_CONVECTION && USE_RADIATION
    heatLossMode = "conv_rad";
elseif USE_CONVECTION
    heatLossMode = "convection_only";
elseif USE_RADIATION
    heatLossMode = "radiation_only";
else
    heatLossMode = "conduction_laser_only";
end

if ~exist(outputFolder, "dir")
    mkdir(outputFolder);
end

%% LASER PARAMETERS
P0 = 5000;                              % W
ALPHA_ATM = 1.65e-4;                    % 1/m
WAVELENGTH = 1064e-9;                   % m
D = 0.1;                                % m
M2 = 1.5;                               % -

% Laser origin
% This is automatically moved outside the drone after the geometry
% dimensions are determined.
laser_origin_world = [0.0; 0.0; 0.0];

% Initial laser angle
theta_0 = 0;

%% MATERIAL SUMMARY
fprintf("============================================================\n");
fprintf(" DRONE THERMAL SIMULATION\n");
fprintf("============================================================\n");
fprintf("Convection: %s\n", ternaryString(USE_CONVECTION, "ENABLED", "DISABLED"));
fprintf("Radiation:   %s\n", ternaryString(USE_RADIATION, "ENABLED", "DISABLED"));
fprintf("Maximum life: %.1f s\n", t_final);
fprintf("Time step:    %.3f s\n", dt);
fprintf("Materials:    %d\n", nMaterials);
fprintf("Frequencies:  %d\n", nFreq);
fprintf("============================================================\n");

for materialIndex = 1:nMaterials
    fprintf("%-20s | rho = %7.1f kg/m^3 | cp = %7.1f J/kgK | k = %8.3f W/mK | threshold = %8.2f K\n", ...
        materials(materialIndex).displayName, ...
        materials(materialIndex).rho, ...
        materials(materialIndex).cp, ...
        materials(materialIndex).k, ...
        materials(materialIndex).melting);
end

% IMPORT GEOMETRY

fprintf("\nIMPORTING DRONE GEOMETRY\n");

g = fegeometry(STEP_FILE);

fprintf("Number of cells: %d\n", g.NumCells);
fprintf("Number of faces: %d\n", g.NumFaces);

% DISPLAY GEOMETRY

fig = figure(...
    "Name", "Drone Geometry", ...
    "Visible", "on");

pdegplot(g, ...
    FaceLabels="on", ...
    CellLabels="on", ...
    FaceAlpha=0.25);

axis equal;
grid on;

xlabel("x [m]");
ylabel("y [m]");
zlabel("z [m]");

title("Drone Geometry");

saveas(fig, fullfile(outputFolder, "Drone_Geometry.png"));

% CREATE FEM MODEL

model = femodel(...
    AnalysisType="thermalTransient", ...
    Geometry=g);

% Required by MATLAB when radiation is enabled.
model.StefanBoltzmann = sigma;

ALL_CELLS = 1:g.NumCells;

%% INITIAL TEMPERATURE

model.CellIC = cellIC(Temperature=T0);


% GENERATE FEM MESH

fprintf("\nGENERATING FEM MESH\n");

model = generateMesh(...
    model, ...
    Hmax=meshSize);

fprintf("Number of nodes: %d\n", ...
    size(model.Geometry.Mesh.Nodes, 2));

fprintf("Number of elements: %d\n", ...
    size(model.Geometry.Mesh.Elements, 2));

 
% DISPLAY MESH
 
fig = figure(...
    "Name", "Drone FEM Mesh", ...
    "Visible", "on");

pdemesh(model.Geometry);

axis equal;
grid on;

xlabel("x [m]");
ylabel("y [m]");
zlabel("z [m]");

title("Drone FEM Mesh");

saveas(fig, ...
    fullfile(outputFolder, "Drone_FEM_Mesh.png"));

 
% GEOMETRY INFORMATION
 

nodes = model.Geometry.Mesh.Nodes;

meshNodes = nodes;

tetElements = model.Geometry.Mesh.Elements;

x_nodes = nodes(1, :);
y_nodes = nodes(2, :);
z_nodes = nodes(3, :);

x_min = min(x_nodes);
x_max = max(x_nodes);

y_min = min(y_nodes);
y_max = max(y_nodes);

z_min = min(z_nodes);
z_max = max(z_nodes);

box_length = x_max - x_min;
box_width = y_max - y_min;
box_height = z_max - z_min;

box_centroid = [...
    (x_min + x_max) / 2;
    (y_min + y_max) / 2;
    (z_min + z_max) / 2];

fprintf("\nDRONE GEOMETRY\n");

fprintf("Length:   %.4f m\n", box_length);
fprintf("Width:    %.4f m\n", box_width);
fprintf("Height:   %.4f m\n", box_height);

fprintf("Centroid: [%.4f, %.4f, %.4f] m\n", ...
    box_centroid(1), ...
    box_centroid(2), ...
    box_centroid(3));

 
% LASER TRAJECTORY
 

% Use the smaller horizontal dimension to define the laser path.
trajectory_radius = 0.40 * min(box_length, box_width);

laser_target_z = box_centroid(3);

trajectory_theta = linspace(...
    0, ...
    2*pi, ...
    500);

trajectory_x = ...
    box_centroid(1) + ...
    trajectory_radius .* cos(trajectory_theta);

trajectory_y = ...
    box_centroid(2) + ...
    trajectory_radius .* sin(trajectory_theta);

trajectory_z = ...
    laser_target_z .* ones(size(trajectory_theta));

 
% MOVE LASER SOURCE OUTSIDE THE DRONE
 

geometryDiagonal = sqrt(...
    box_length^2 + ...
    box_width^2 + ...
    box_height^2);

laser_standoff = max(2.0, 5.0 * geometryDiagonal);

laser_origin_world = ...
    box_centroid + [0; 0; laser_standoff];

fprintf("\nLASER CONFIGURATION\n");

fprintf("Laser origin: [%.4f, %.4f, %.4f] m\n", ...
    laser_origin_world(1), ...
    laser_origin_world(2), ...
    laser_origin_world(3));

fprintf("Laser target center: [%.4f, %.4f, %.4f] m\n", ...
    box_centroid(1), ...
    box_centroid(2), ...
    box_centroid(3));

fprintf("Laser trajectory radius: %.4f m\n", ...
    trajectory_radius);

 
% DISPLAY LASER TRAJECTORY
 

fig = figure(...
    "Name", "Laser Trajectory", ...
    "Visible", "on");

pdegplot(...
    model.Geometry, ...
    FaceAlpha=0.15);

hold on;

plot3(...
    trajectory_x, ...
    trajectory_y, ...
    trajectory_z, ...
    "LineWidth", 2);

scatter3(...
    box_centroid(1), ...
    box_centroid(2), ...
    box_centroid(3), ...
    50, ...
    "filled");

scatter3(...
    laser_origin_world(1), ...
    laser_origin_world(2), ...
    laser_origin_world(3), ...
    60, ...
    "filled");

axis equal;
grid on;

xlabel("x [m]");
ylabel("y [m]");
zlabel("z [m]");

title("Laser Trajectory");

legend({...
    "Drone", ...
    "Laser trajectory", ...
    "Drone centroid", ...
    "Laser source"}, ...
    "Location", "best");

saveas(fig, ...
    fullfile(outputFolder, "Laser_Trajectory.png"));

 
% SURFACE TRIANGULATION FOR LASER ENERGY INTEGRATION
 

fprintf("\nLASER ENERGY SURFACE\n");

if size(tetElements, 1) < 4
    error(...
        "Unexpected FEM mesh: each tetrahedral element must have at least 4 nodes.");
end

% Only use the four corner nodes of each tetrahedron.
% This avoids problems caused by quadratic/midside nodes.
tetCornerElements = tetElements(1:4, :)';

TR = triangulation(...
    tetCornerElements, ...
    meshNodes');

[boundaryTriangles, ~] = freeBoundary(TR);

fprintf("Boundary triangles: %d\n", ...
    size(boundaryTriangles, 1));

 
% CALCULATE BOUNDARY TRIANGLE AREAS
 

p1 = meshNodes(:, boundaryTriangles(:,1));
p2 = meshNodes(:, boundaryTriangles(:,2));
p3 = meshNodes(:, boundaryTriangles(:,3));

triangleVectors1 = p2 - p1;
triangleVectors2 = p3 - p1;

triangleCross = cross(...
    triangleVectors1', ...
    triangleVectors2', ...
    2);

boundaryTriangleAreas = ...
    0.5 .* vecnorm(...
    triangleCross, ...
    2, ...
    2);

boundaryTriangleCentroids = ...
    (p1 + p2 + p3)' ./ 3;

totalSurfaceArea = ...
    sum(boundaryTriangleAreas);

fprintf("Boundary surface area: %.6f m^2\n", ...
    totalSurfaceArea);

 
% PRECOMPUTE TETRAHEDRAL VOLUMES
 

a = ...
    meshNodes(:, tetElements(2,:)) - ...
    meshNodes(:, tetElements(1,:));

b = ...
    meshNodes(:, tetElements(3,:)) - ...
    meshNodes(:, tetElements(1,:));

c = ...
    meshNodes(:, tetElements(4,:)) - ...
    meshNodes(:, tetElements(1,:));

tetVolumes = ...
    abs(dot(...
    a, ...
    cross(b, c, 1), ...
    1)) ./ 6;

 
% RESULTS STORAGE
 

% Each dimension is material x frequency.

maxTemperature = ...
    zeros(nMaterials, nFreq);

finalTemperature = ...
    zeros(nMaterials, nFreq);

averageFinalTemperature = ...
    zeros(nMaterials, nFreq);

timeOfMaximum = ...
    zeros(nMaterials, nFreq);

lifeTime = ...
    zeros(nMaterials, nFreq);

averageH = ...
    zeros(nMaterials, nFreq);

phaseTerminated = ...
    false(nMaterials, nFreq);

terminationReason = ...
    strings(nMaterials, nFreq);

maxLaserPower = ...
    zeros(nMaterials, nFreq);

totalLaserEnergy = ...
    zeros(nMaterials, nFreq);

finalStoredThermalEnergy = ...
    zeros(nMaterials, nFreq);

maxStoredThermalEnergy = ...
    zeros(nMaterials, nFreq);

surfaceArea = ...
    repmat(...
    totalSurfaceArea, ...
    nMaterials, ...
    nFreq);

timeHistories = ...
    cell(nMaterials, nFreq);

temperatureHistories = ...
    cell(nMaterials, nFreq);

laserPowerHistories = ...
    cell(nMaterials, nFreq);

thermalEnergyHistories = ...
    cell(nMaterials, nFreq);

 
% MATERIAL LOOP
 

for materialIndex = 1:nMaterials

    material = materials(materialIndex);

    fprintf("\n");
    fprintf("############################################################\n");
    fprintf(" MATERIAL %d OF %d: %s\n", ...
        materialIndex, ...
        nMaterials, ...
        material.displayName);
    fprintf("############################################################\n");

    fprintf("rho = %.1f kg/m^3\n", ...
        material.rho);

    fprintf("cp  = %.1f J/(kg*K)\n", ...
        material.cp);

    fprintf("k   = %.3f W/(m*K)\n", ...
        material.k);

    fprintf("Laser absorptivity = %.3f\n", ...
        material.absorptivity);

    fprintf("Termination threshold = %.2f K (%.2f C)\n", ...
        material.melting, ...
        material.melting - 273.15);

    %% Assign this material to the entire drone.

    model.MaterialProperties(ALL_CELLS) = ...
        materialProperties(...
        ThermalConductivity=material.k, ...
        MassDensity=material.rho, ...
        SpecificHeat=material.cp);

    % FREQUENCY LOOP

    for freqIndex = 1:nFreq

        frequency_Hz = ...
            rotation_frequencies(freqIndex);

        omega_z = ...
            2 * pi * frequency_Hz;

        fprintf("\n------------------------------------------------------------\n");

        fprintf("%s | %.2f Hz | %d/%d\n", ...
            material.displayName, ...
            frequency_Hz, ...
            freqIndex, ...
            nFreq);

        fprintf("Angular velocity: %.4f rad/s\n", ...
            omega_z);

        fprintf("RPM: %.2f\n", ...
            frequency_Hz * 60);

        fprintf("------------------------------------------------------------\n");

        %% Reset initial condition.

        model.CellIC = ...
            cellIC(Temperature=T0);

        % APPLY LASER TO ENTIRE EXTERNAL BOUNDARY

        laserHeatFunction = ...
            @(location, state) ...
            laserHeatFluxCircular(...
            location, ...
            state, ...
            box_centroid, ...
            trajectory_radius, ...
            omega_z, ...
            theta_0, ...
            laser_origin_world, ...
            P0, ...
            ALPHA_ATM, ...
            WAVELENGTH, ...
            D, ...
            M2, ...
            material.absorptivity);

 
        % APPLY THERMAL BOUNDARY CONDITIONS
 
        % One face-load object is applied to the complete external
        % boundary. The two switches above control convection and
        % radiation independently.

        if USE_CONVECTION
            convectionFunction = ...
                @(location, state) ...
                convectionCoefficientRotation(...
                location, ...
                omega_z, ...
                box_centroid, ...
                air_density, ...
                air_viscosity, ...
                air_conductivity, ...
                air_prandtl, ...
                L_characteristic, ...
                h_free);
        end

        if USE_CONVECTION && USE_RADIATION

            model.FaceLoad = ...
                faceLoad(...
                Heat=laserHeatFunction, ...
                ConvectionCoefficient=convectionFunction, ...
                AmbientTemperature=Tinf, ...
                Emissivity=material.emissivity);

        elseif USE_CONVECTION

            model.FaceLoad = ...
                faceLoad(...
                Heat=laserHeatFunction, ...
                ConvectionCoefficient=convectionFunction, ...
                AmbientTemperature=Tinf);

        elseif USE_RADIATION

            model.FaceLoad = ...
                faceLoad(...
                Heat=laserHeatFunction, ...
                AmbientTemperature=Tinf, ...
                Emissivity=material.emissivity);

        else

            model.FaceLoad = ...
                faceLoad(Heat=laserHeatFunction);

        end

        %% Histories for this material/frequency case.

        currentTime = 0;

        currentTemperature = ...
            T0 * ones(size(meshNodes, 2), 1);

        timeHistory = 0;

        temperatureHistory = ...
            currentTemperature;

        laserPowerHistory = 0;

        thermalEnergyHistory = 0;

        terminatedByPhase = false;

 
        % WHILE LOOP
 

        % Continue until either 60 s is reached or Tmax reaches the
        % selected material's threshold.

        while currentTime < t_final && ...
                max(currentTemperature) < material.melting

            nextTime = ...
                min(currentTime + dt, t_final);

 
            % CALCULATE LASER POWER
 

            location = struct(...
                "x", boundaryTriangleCentroids(:,1)', ...
                "y", boundaryTriangleCentroids(:,2)', ...
                "z", boundaryTriangleCentroids(:,3)');

            state = struct(...
                "time", nextTime);

            qTriangle = ...
                laserHeatFluxCircular(...
                location, ...
                state, ...
                box_centroid, ...
                trajectory_radius, ...
                omega_z, ...
                theta_0, ...
                laser_origin_world, ...
                P0, ...
                ALPHA_ATM, ...
                WAVELENGTH, ...
                D, ...
                M2, ...
                material.absorptivity);

            qTriangle = ...
                reshape(qTriangle, [], 1);

            % Integrate heat flux over the complete boundary.
            laserPower = ...
                sum(qTriangle .* boundaryTriangleAreas);

            % Prevent numerical integration from producing a
            % physically impossible absorbed power.
            laserRange = ...
                norm(box_centroid - laser_origin_world);

            availableIncidentPower = ...
                P0 * exp(-ALPHA_ATM * laserRange);

            maximumAbsorbedPower = ...
                material.absorptivity * ...
                availableIncidentPower;

            laserPower = ...
                min(max(laserPower, 0), ...
                maximumAbsorbedPower);

 
            % SET INITIAL TEMPERATURE FOR THIS SHORT STEP
 

            if currentTime > 0

                previousNodes = ...
                    meshNodes;

                previousTemperature = ...
                    currentTemperature;

                T_initial_function = ...
                    @(location) ...
                    interpolatePreviousTemperature(...
                    location, ...
                    previousNodes, ...
                    previousTemperature);

                model.CellIC = ...
                    cellIC(...
                    Temperature=T_initial_function);

            end

 
            % SOLVE ONE SHORT INTERVAL
 

            stepResults = ...
                solve(...
                model, ...
                [currentTime, nextTime]);

            currentTemperature = ...
                stepResults.Temperature(:, end);

            currentTime = ...
                nextTime;

 
            % STORE HISTORIES
 

            timeHistory(end+1) = ...
                currentTime; %#ok<SAGROW>

            temperatureHistory(:, end+1) = ...
                currentTemperature; %#ok<SAGROW>

            laserPowerHistory(end+1) = ...
                laserPower; %#ok<SAGROW>

 
            % STORED THERMAL ENERGY
 

            tetTemperature = ...
                mean(...
                currentTemperature(...
                tetElements(1:4,:)), ...
                1);

            currentThermalEnergy = ...
                sum(...
                material.rho .* ...
                material.cp .* ...
                (tetTemperature - T0) .* ...
                tetVolumes);

            thermalEnergyHistory(end+1) = ...
                currentThermalEnergy; %#ok<SAGROW>

 
            % IDEALIZED LASER TEMPERATURE INCREASE
 

            totalAbsorbedEnergySoFar = ...
                trapz(...
                timeHistory, ...
                laserPowerHistory);

            droneVolume = ...
                sum(tetVolumes);

            droneMass = ...
                material.rho * droneVolume;

            idealizedTemperatureRise = ...
                totalAbsorbedEnergySoFar / ...
                max(droneMass * material.cp, eps);

 
            % PRINT PROGRESS
 

            if abs(currentTime - round(currentTime)) < dt/2 || ...
                    currentTime >= t_final || ...
                    max(currentTemperature) >= material.melting

                fprintf(...
                    "t = %6.2f s | Tmax = %8.2f C | laser P = %9.3f W | ideal dT = %8.3f C\n", ...
                    currentTime, ...
                    max(currentTemperature) - 273.15, ...
                    laserPower, ...
                    idealizedTemperatureRise);

            end

 
            % CHECK PHASE CHANGE
 

            if max(currentTemperature) >= ...
                    material.melting

                terminatedByPhase = true;

                fprintf("\n");
                fprintf("*** TEMPERATURE THRESHOLD REACHED ***\n");

                fprintf("Material: %s\n", ...
                    material.displayName);

                fprintf("Time: %.4f s\n", ...
                    currentTime);

                fprintf("Maximum temperature: %.2f C\n", ...
                    max(currentTemperature) - 273.15);

                fprintf("Threshold: %.2f C\n", ...
                    material.melting - 273.15);

                break;

            end

        end

 
        % DETERMINE TERMINATION REASON
 

        if terminatedByPhase

            terminationReason(...
                materialIndex, ...
                freqIndex) = ...
                "Temperature threshold";

        else

            terminationReason(...
                materialIndex, ...
                freqIndex) = ...
                "60 second limit";

        end

 
        % FINAL RESULTS
 

        TmaxTime = ...
            max(temperatureHistory, [], 1);

        maxTemperature(...
            materialIndex, ...
            freqIndex) = ...
            max(TmaxTime);

        finalTemperature(...
            materialIndex, ...
            freqIndex) = ...
            TmaxTime(end);

        averageFinalTemperature(...
            materialIndex, ...
            freqIndex) = ...
            mean(temperatureHistory(:, end));

        [~, maxIndex] = ...
            max(TmaxTime);

        timeOfMaximum(...
            materialIndex, ...
            freqIndex) = ...
            timeHistory(maxIndex);

        lifeTime(...
            materialIndex, ...
            freqIndex) = ...
            currentTime;

        %% AVERAGE ROTATIONAL CONVECTION COEFFICIENT
        if USE_CONVECTION
            nodeX = meshNodes(1, :);
            nodeY = meshNodes(2, :);

            radialDistance = sqrt(...
                (nodeX - box_centroid(1)).^2 + ...
                (nodeY - box_centroid(2)).^2);

            velocity = abs(omega_z) .* radialDistance;

            Re = air_density .* velocity .* ...
                L_characteristic ./ air_viscosity;
            Re = max(Re, 1);

            Nu = 0.664 .* sqrt(Re) .* ...
                air_prandtl.^(1/3);

            turbulent = Re >= 5e5;
            Nu(turbulent) = ...
                (0.037 .* Re(turbulent).^0.8 - 871) .* ...
                air_prandtl.^(1/3);

            h_nodes = h_free + ...
                Nu .* air_conductivity ./ L_characteristic;

            averageH(materialIndex, freqIndex) = mean(h_nodes);
        else
            averageH(materialIndex, freqIndex) = 0;
        end

        phaseTerminated(...
            materialIndex, ...
            freqIndex) = ...
            terminatedByPhase;

        maxLaserPower(...
            materialIndex, ...
            freqIndex) = ...
            max(laserPowerHistory);

        totalLaserEnergy(...
            materialIndex, ...
            freqIndex) = ...
            trapz(...
            timeHistory, ...
            laserPowerHistory);

        finalStoredThermalEnergy(...
            materialIndex, ...
            freqIndex) = ...
            thermalEnergyHistory(end);

        maxStoredThermalEnergy(...
            materialIndex, ...
            freqIndex) = ...
            max(thermalEnergyHistory);

        timeHistories{...
            materialIndex, ...
            freqIndex} = ...
            timeHistory;

        temperatureHistories{...
            materialIndex, ...
            freqIndex} = ...
            temperatureHistory;

        laserPowerHistories{...
            materialIndex, ...
            freqIndex} = ...
            laserPowerHistory;

        thermalEnergyHistories{...
            materialIndex, ...
            freqIndex} = ...
            thermalEnergyHistory;

 
        % FORMATTED FILENAMES
 

        materialTag = ...
            material.name;

        frequencyTag = ...
            strrep(...
            sprintf("%.2f", frequency_Hz), ...
            ".", ...
            "p");

 
        % FINAL 3D TEMPERATURE GRAPH
 

        fig = figure(...
            "Name", ...
            sprintf(...
            "Temperature %s %.2f Hz", ...
            material.displayName, ...
            frequency_Hz), ...
            "Visible", ...
            "on");

        pdeplot3D(...
            stepResults.Mesh, ...
            ColorMapData=...
            temperatureHistory(:, end) - 273.15);

        axis equal;
        grid on;
        colorbar;

        xlabel("x [m]");
        ylabel("y [m]");
        zlabel("z [m]");

        title(...
            sprintf(...
            "Final Temperature - %s - %.2f Hz", ...
            material.displayName, ...
            frequency_Hz));

        filename = ...
            fullfile(...
            outputFolder, ...
            sprintf(...
            "Temperature3D_%s_%sHz.png", ...
            materialTag, ...
            frequencyTag));

        saveas(fig, filename);

 
        % MAXIMUM TEMPERATURE HISTORY
 

        fig = figure(...
            "Name", ...
            sprintf(...
            "Temperature History %s %.2f Hz", ...
            material.displayName, ...
            frequency_Hz), ...
            "Visible", ...
            "on");

        plot(...
            timeHistory, ...
            TmaxTime - 273.15, ...
            "LineWidth", ...
            2);

        hold on;

        yline(...
            material.melting - 273.15, ...
            "--", ...
            "Threshold", ...
            "LineWidth", ...
            1.5);

        grid on;

        xlabel("Time [s]");
        ylabel("Maximum Temperature [C]");

        title(...
            sprintf(...
            "Maximum Temperature - %s - %.2f Hz", ...
            material.displayName, ...
            frequency_Hz));

        legend(...
            {"Maximum temperature", ...
             "Termination threshold"}, ...
            "Location", ...
            "best");

        filename = ...
            fullfile(...
            outputFolder, ...
            sprintf(...
            "TemperatureHistory_%s_%sHz.png", ...
            materialTag, ...
            frequencyTag));

        saveas(fig, filename);

 
        % LASER POWER AND ENERGY HISTORY
 

        fig = figure(...
            "Name", ...
            sprintf(...
            "Laser Energy %s %.2f Hz", ...
            material.displayName, ...
            frequency_Hz), ...
            "Visible", ...
            "on");

        yyaxis left;

        plot(...
            timeHistory, ...
            laserPowerHistory, ...
            "LineWidth", ...
            2);

        ylabel("Absorbed Laser Power [W]");

        yyaxis right;

        plot(...
            timeHistory, ...
            cumtrapz(...
            timeHistory, ...
            laserPowerHistory), ...
            "LineWidth", ...
            2);

        ylabel("Cumulative Laser Energy [J]");

        grid on;

        xlabel("Time [s]");

        title(...
            sprintf(...
            "Laser Energy - %s - %.2f Hz", ...
            material.displayName, ...
            frequency_Hz));

        filename = ...
            fullfile(...
            outputFolder, ...
            sprintf(...
            "LaserEnergy_%s_%sHz.png", ...
            materialTag, ...
            frequencyTag));

        saveas(fig, filename);

 
        % STORED THERMAL ENERGY HISTORY
 

        fig = figure(...
            "Name", ...
            sprintf(...
            "Thermal Energy %s %.2f Hz", ...
            material.displayName, ...
            frequency_Hz), ...
            "Visible", ...
            "on");

        plot(...
            timeHistory, ...
            thermalEnergyHistory, ...
            "LineWidth", ...
            2);

        grid on;

        xlabel("Time [s]");

        ylabel(...
            "Stored Thermal Energy Above T0 [J]");

        title(...
            sprintf(...
            "Stored Thermal Energy - %s - %.2f Hz", ...
            material.displayName, ...
            frequency_Hz));

        filename = ...
            fullfile(...
            outputFolder, ...
            sprintf(...
            "ThermalEnergy_%s_%sHz.png", ...
            materialTag, ...
            frequencyTag));

        saveas(fig, filename);

 
        % LASER TEMPERATURE RISE
 

        droneVolume = ...
            sum(tetVolumes);

        droneMass = ...
            material.rho * droneVolume;

        idealTemperatureRise = ...
            cumtrapz(...
            timeHistory, ...
            laserPowerHistory) ./ ...
            max(droneMass * material.cp, eps);

        femTemperatureRise = ...
            TmaxTime - T0;

        fig = figure(...
            "Name", ...
            sprintf(...
            "Laser Temperature Rise %s %.2f Hz", ...
            material.displayName, ...
            frequency_Hz), ...
            "Visible", ...
            "on");

        plot(...
            timeHistory, ...
            idealTemperatureRise, ...
            "LineWidth", ...
            2);

        hold on;

        plot(...
            timeHistory, ...
            femTemperatureRise, ...
            "LineWidth", ...
            2);

        grid on;

        xlabel("Time [s]");
        ylabel("Temperature Rise [K]");

        title(...
            sprintf(...
            "Laser Temperature Rise - %s - %.2f Hz", ...
            material.displayName, ...
            frequency_Hz));

        legend(...
            {"Ideal energy balance", ...
             "FEM maximum temperature"}, ...
            "Location", ...
            "best");

        filename = ...
            fullfile(...
            outputFolder, ...
            sprintf(...
            "LaserTemperatureRise_%s_%sHz.png", ...
            materialTag, ...
            frequencyTag));

        saveas(fig, filename);

 
        % PRINT CASE SUMMARY
 

        fprintf("\nRESULTS: %s | %.2f Hz\n", ...
            material.displayName, ...
            frequency_Hz);

        fprintf(...
            "Maximum temperature:          %.2f C\n", ...
            maxTemperature(materialIndex, freqIndex) - 273.15);

        fprintf(...
            "Final maximum temperature:    %.2f C\n", ...
            finalTemperature(materialIndex, freqIndex) - 273.15);

        fprintf(...
            "Average final temperature:    %.2f C\n", ...
            averageFinalTemperature(materialIndex, freqIndex) - 273.15);

        fprintf(...
            "Average convection coefficient: %.2f W/(m^2*K)\n", ...
            averageH(materialIndex, freqIndex));

        fprintf(...
            "Life time:                    %.4f s\n", ...
            lifeTime(materialIndex, freqIndex));

        fprintf(...
            "Termination:                  %s\n", ...
            terminationReason(materialIndex, freqIndex));

        fprintf(...
            "Time of maximum:              %.4f s\n", ...
            timeOfMaximum(materialIndex, freqIndex));

        fprintf(...
            "Maximum absorbed power:       %.4f W\n", ...
            maxLaserPower(materialIndex, freqIndex));

        fprintf(...
            "Total absorbed energy:        %.4f J\n", ...
            totalLaserEnergy(materialIndex, freqIndex));

        fprintf(...
            "Final stored thermal energy:  %.4f J\n", ...
            finalStoredThermalEnergy(materialIndex, freqIndex));

        fprintf(...
            "Maximum stored thermal energy: %.4f J\n", ...
            maxStoredThermalEnergy(materialIndex, freqIndex));

    end
end

 
% RESULTS TABLE - ONE TABLE PER MATERIAL
 

allTables = ...
    cell(nMaterials, 1);

for materialIndex = 1:nMaterials

    material = ...
        materials(materialIndex);

    N = nFreq;

    frequencyColumn = ...
        reshape(...
        rotation_frequencies, ...
        N, ...
        1);

    rpmColumn = ...
        reshape(...
        rotation_frequencies .* 60, ...
        N, ...
        1);

    angularVelocityColumn = ...
        reshape(...
        2 .* pi .* rotation_frequencies, ...
        N, ...
        1);

    maximumTemperatureColumn = ...
        reshape(...
        maxTemperature(materialIndex, :)' - 273.15, ...
        N, ...
        1);

    finalMaximumTemperatureColumn = ...
        reshape(...
        finalTemperature(materialIndex, :)' - 273.15, ...
        N, ...
        1);

    averageFinalTemperatureColumn = ...
        reshape(...
        averageFinalTemperature(materialIndex, :)' - 273.15, ...
        N, ...
        1);

    phaseChangeThresholdColumn = ...
        repmat(...
        material.melting - 273.15, ...
        N, ...
        1);

    lifeTimeColumn = ...
        reshape(...
        lifeTime(materialIndex, :)', ...
        N, ...
        1);

    phaseTerminatedColumn = ...
        reshape(...
        phaseTerminated(materialIndex, :)', ...
        N, ...
        1);

    terminationReasonColumn = ...
        reshape(...
        terminationReason(materialIndex, :)', ...
        N, ...
        1);

    timeOfMaximumColumn = ...
        reshape(...
        timeOfMaximum(materialIndex, :)', ...
        N, ...
        1);

    maxLaserPowerColumn = ...
        reshape(...
        maxLaserPower(materialIndex, :)', ...
        N, ...
        1);

    totalLaserEnergyColumn = ...
        reshape(...
        totalLaserEnergy(materialIndex, :)', ...
        N, ...
        1);

    finalStoredThermalEnergyColumn = ...
        reshape(...
        finalStoredThermalEnergy(materialIndex, :)', ...
        N, ...
        1);

    maxStoredThermalEnergyColumn = ...
        reshape(...
        maxStoredThermalEnergy(materialIndex, :)', ...
        N, ...
        1);

    surfaceAreaColumn = ...
        repmat(...
        totalSurfaceArea, ...
        N, ...
        1);

    averageHColumn = ...
        reshape(averageH(materialIndex, :)', N, 1);

    resultsTable = table(...
        frequencyColumn, ...
        rpmColumn, ...
        angularVelocityColumn, ...
        maximumTemperatureColumn, ...
        finalMaximumTemperatureColumn, ...
        averageFinalTemperatureColumn, ...
        phaseChangeThresholdColumn, ...
        lifeTimeColumn, ...
        averageHColumn, ...
        phaseTerminatedColumn, ...
        terminationReasonColumn, ...
        timeOfMaximumColumn, ...
        maxLaserPowerColumn, ...
        totalLaserEnergyColumn, ...
        finalStoredThermalEnergyColumn, ...
        maxStoredThermalEnergyColumn, ...
        surfaceAreaColumn);

    resultsTable.Properties.VariableNames = {...
        "Frequency_Hz", ...
        "RPM", ...
        "AngularVelocity_rad_s", ...
        "MaximumTemperature_C", ...
        "FinalMaximumTemperature_C", ...
        "AverageFinalTemperature_C", ...
        "TerminationThreshold_C", ...
        "LifeTime_s", ...
        "AverageConvection_W_m2K", ...
        "TerminatedByTemperature", ...
        "TerminationReason", ...
        "TimeOfMaximum_s", ...
        "MaxAbsorbedLaserPower_W", ...
        "TotalLaserEnergy_J", ...
        "FinalStoredThermalEnergy_J", ...
        "MaxStoredThermalEnergy_J", ...
        "LaserSurfaceArea_m2"};

    allTables{materialIndex} = ...
        resultsTable;

    fprintf("\n");
    fprintf("============================================================\n");
    fprintf(" FINAL RESULTS: %s\n", ...
        material.displayName);
    fprintf("============================================================\n");

    disp(resultsTable);

    materialTag = ...
        material.name;

    resultsFilename = ...
        fullfile(...
        outputFolder, ...
        sprintf(...
        "thermal_results_%s.csv", ...
        materialTag));

    writetable(...
        resultsTable, ...
        resultsFilename);

end

 
% COMPARISON TABLE - ALL MATERIALS / FREQUENCIES
 

numberOfRows = ...
    nMaterials * nFreq;

materialColumn = ...
    strings(numberOfRows, 1);

materialDisplayColumn = ...
    strings(numberOfRows, 1);

frequencyColumn = ...
    zeros(numberOfRows, 1);

rpmColumn = ...
    zeros(numberOfRows, 1);

maximumTemperatureColumn = ...
    zeros(numberOfRows, 1);

finalTemperatureColumn = ...
    zeros(numberOfRows, 1);

thresholdColumn = ...
    zeros(numberOfRows, 1);

lifeTimeColumn = ...
    zeros(numberOfRows, 1);

averageHColumn = ...
    zeros(numberOfRows, 1);

terminatedColumn = ...
    false(numberOfRows, 1);

terminationReasonColumn = ...
    strings(numberOfRows, 1);

maxLaserPowerColumn = ...
    zeros(numberOfRows, 1);

totalLaserEnergyColumn = ...
    zeros(numberOfRows, 1);

finalThermalEnergyColumn = ...
    zeros(numberOfRows, 1);

maxThermalEnergyColumn = ...
    zeros(numberOfRows, 1);

row = 0;

for materialIndex = 1:nMaterials

    for freqIndex = 1:nFreq

        row = row + 1;

        materialColumn(row) = ...
            materials(materialIndex).name;

        materialDisplayColumn(row) = ...
            materials(materialIndex).displayName;

        frequencyColumn(row) = ...
            rotation_frequencies(freqIndex);

        rpmColumn(row) = ...
            rotation_frequencies(freqIndex) * 60;

        maximumTemperatureColumn(row) = ...
            maxTemperature(materialIndex, freqIndex) - 273.15;

        finalTemperatureColumn(row) = ...
            finalTemperature(materialIndex, freqIndex) - 273.15;

        thresholdColumn(row) = ...
            materials(materialIndex).melting - 273.15;

        lifeTimeColumn(row) = ...
            lifeTime(materialIndex, freqIndex);

        averageHColumn(row) = ...
            averageH(materialIndex, freqIndex);

        terminatedColumn(row) = ...
            phaseTerminated(materialIndex, freqIndex);

        terminationReasonColumn(row) = ...
            terminationReason(materialIndex, freqIndex);

        maxLaserPowerColumn(row) = ...
            maxLaserPower(materialIndex, freqIndex);

        totalLaserEnergyColumn(row) = ...
            totalLaserEnergy(materialIndex, freqIndex);

        finalThermalEnergyColumn(row) = ...
            finalStoredThermalEnergy(materialIndex, freqIndex);

        maxThermalEnergyColumn(row) = ...
            maxStoredThermalEnergy(materialIndex, freqIndex);

    end

end

comparisonTable = table(...
    materialColumn, ...
    materialDisplayColumn, ...
    frequencyColumn, ...
    rpmColumn, ...
    maximumTemperatureColumn, ...
    finalTemperatureColumn, ...
    thresholdColumn, ...
    lifeTimeColumn, ...
    averageHColumn, ...
    terminatedColumn, ...
    terminationReasonColumn, ...
    maxLaserPowerColumn, ...
    totalLaserEnergyColumn, ...
    finalThermalEnergyColumn, ...
    maxThermalEnergyColumn);

comparisonTable.Properties.VariableNames = {...
    "Material", ...
    "MaterialDisplayName", ...
    "Frequency_Hz", ...
    "RPM", ...
    "MaximumTemperature_C", ...
    "FinalMaximumTemperature_C", ...
    "TerminationThreshold_C", ...
    "LifeTime_s", ...
    "AverageConvection_W_m2K", ...
    "TerminatedByTemperature", ...
    "TerminationReason", ...
    "MaxAbsorbedLaserPower_W", ...
    "TotalLaserEnergy_J", ...
    "FinalStoredThermalEnergy_J", ...
    "MaxStoredThermalEnergy_J"};

comparisonFilename = ...
    fullfile(...
    outputFolder, ...
    "thermal_results_all_materials.csv");

writetable(...
    comparisonTable, ...
    comparisonFilename);

fprintf("\n");
fprintf("============================================================\n");
fprintf(" ALL-MATERIAL RESULTS\n");
fprintf("============================================================\n");

disp(comparisonTable);

 
% COMPARISON GRAPH - MAXIMUM TEMPERATURE
 

fig = figure(...
    "Name", ...
    "Maximum Temperature - All Materials");

hold on;

for materialIndex = 1:nMaterials

    plot(...
        rotation_frequencies, ...
        maxTemperature(materialIndex, :) - 273.15, ...
        "-o", ...
        "LineWidth", ...
        2, ...
        "DisplayName", ...
        materials(materialIndex).displayName);

end

grid on;

xlabel("Rotation Frequency [Hz]");
ylabel("Maximum Temperature [C]");

title("Maximum Temperature vs Frequency");

legend(...
    "Location", ...
    "best");

filename = ...
    fullfile(...
    outputFolder, ...
    "Comparison_MaximumTemperature_AllMaterials.png");

saveas(fig, filename);

 
% COMPARISON GRAPH - LIFETIME
 

fig = figure(...
    "Name", ...
    "Lifetime - All Materials");

hold on;

for materialIndex = 1:nMaterials

    plot(...
        rotation_frequencies, ...
        lifeTime(materialIndex, :), ...
        "-o", ...
        "LineWidth", ...
        2, ...
        "DisplayName", ...
        materials(materialIndex).displayName);

end

yline(...
    t_final, ...
    "--", ...
    "60 s limit", ...
    "LineWidth", ...
    1.5);

grid on;

xlabel("Rotation Frequency [Hz]");
ylabel("Thermal Lifetime [s]");

title("Thermal Lifetime vs Frequency");

legend(...
    "Location", ...
    "best");

filename = ...
    fullfile(...
    outputFolder, ...
    "Comparison_Lifetime_AllMaterials.png");

saveas(fig, filename);

 
% COMPARISON GRAPH - TOTAL LASER ENERGY
 

fig = figure(...
    "Name", ...
    "Laser Energy - All Materials");

hold on;

for materialIndex = 1:nMaterials

    plot(...
        rotation_frequencies, ...
        totalLaserEnergy(materialIndex, :), ...
        "-o", ...
        "LineWidth", ...
        2, ...
        "DisplayName", ...
        materials(materialIndex).displayName);

end

grid on;

xlabel("Rotation Frequency [Hz]");
ylabel("Total Absorbed Laser Energy [J]");

title("Total Laser Energy vs Frequency");

legend(...
    "Location", ...
    "best");

filename = ...
    fullfile(...
    outputFolder, ...
    "Comparison_TotalLaserEnergy_AllMaterials.png");

saveas(fig, filename);

 
% COMPARISON GRAPH - THERMAL ENERGY
 

fig = figure(...
    "Name", ...
    "Thermal Energy - All Materials");

hold on;

for materialIndex = 1:nMaterials

    plot(...
        rotation_frequencies, ...
        finalStoredThermalEnergy(materialIndex, :), ...
        "-o", ...
        "LineWidth", ...
        2, ...
        "DisplayName", ...
        materials(materialIndex).displayName);

end

grid on;

xlabel("Rotation Frequency [Hz]");

ylabel(...
    "Final Stored Thermal Energy Above T0 [J]");

title("Stored Thermal Energy vs Frequency");

legend(...
    "Location", ...
    "best");

filename = ...
    fullfile(...
    outputFolder, ...
    "Comparison_ThermalEnergy_AllMaterials.png");

saveas(fig, filename);

 
% SAVE MATLAB RESULTS
 

matFilename = ...
    fullfile(...
    outputFolder, ...
    "drone_thermal_all_materials.mat");

save(...
    matFilename, ...
    "allTables", ...
    "comparisonTable", ...
    "rotation_frequencies", ...
    "maxTemperature", ...
    "finalTemperature", ...
    "averageFinalTemperature", ...
    "timeOfMaximum", ...
    "lifeTime", ...
    "averageH", ...
    "phaseTerminated", ...
    "terminationReason", ...
    "maxLaserPower", ...
    "totalLaserEnergy", ...
    "finalStoredThermalEnergy", ...
    "maxStoredThermalEnergy", ...
    "surfaceArea", ...
    "box_centroid", ...
    "trajectory_radius", ...
    "laser_origin_world", ...
    "materials", ...
    "USE_CONVECTION", ...
    "USE_RADIATION", ...
    "heatLossMode", ...
    "timeHistories", ...
    "temperatureHistories", ...
    "laserPowerHistories", ...
    "thermalEnergyHistories");

fprintf("\n");
fprintf("============================================================\n");
fprintf(" RESULTS SAVED\n");
fprintf("============================================================\n");

fprintf("Output folder: %s\n", ...
    outputFolder);

fprintf("Combined CSV: %s\n", ...
    comparisonFilename);

fprintf("MAT file:     %s\n", ...
    matFilename);

 
% SMALL DISPLAY HELPER
 
function output = ternaryString(condition, trueString, falseString)
    if condition
        output = trueString;
    else
        output = falseString;
    end
end

 
% LASER HEAT FLUX FUNCTION
 

function q = laserHeatFluxCircular(...
    location, ...
    state, ...
    box_centroid, ...
    trajectory_radius, ...
    omega_z, ...
    theta_0, ...
    laser_origin_world, ...
    P0, ...
    ALPHA_ATM, ...
    WAVELENGTH, ...
    D, ...
    M2, ...
    absorptivity)

    %% TIME

    if isempty(state) || ...
            ~isfield(state, "time") || ...
            isempty(state.time)

        t = 0;

    else

        t = state.time;

    end

    % MATLAB may evaluate a time-dependent boundary condition with
    % an undefined time during setup.
    if any(isnan(t(:)))

        q = NaN(size(location.x));

        return;

    end

    %% LASER TARGET

    theta = ...
        theta_0 + ...
        omega_z .* t;

    target = [...
        box_centroid(1) + ...
        trajectory_radius .* cos(theta);

        box_centroid(2) + ...
        trajectory_radius .* sin(theta);

        box_centroid(3)];

    %% LASER DIRECTION

    laser_direction = ...
        target - ...
        laser_origin_world;

    range = ...
        norm(laser_direction);

    if range < 1e-12

        q = zeros(size(location.x));

        return;

    end

    laser_direction = ...
        laser_direction ./ range;

    %% BEAM WAIST AND WIDTH

    w0 = ...
        D ./ ...
        (pi .* M2);

    w = ...
        sqrt(...
        w0.^2 + ...
        (WAVELENGTH .* range).^2);

    %% ATMOSPHERIC ATTENUATION

    I0 = ...
        P0 .* ...
        exp(-ALPHA_ATM .* range);

    %% SURFACE POSITIONS

    x = ...
        location.x(:);

    y = ...
        location.y(:);

    z = ...
        location.z(:);

    xyz = [...
        x, ...
        y, ...
        z];

    %% DISTANCE FROM LASER TARGET

    relative = ...
        xyz - ...
        target.';

    %% TRANSVERSE LASER BASIS

    referenceVector = ...
        [0; 0; 1];

    if abs(...
            dot(...
            referenceVector, ...
            laser_direction)) > 0.95

        referenceVector = ...
            [0; 1; 0];

    end

    e1 = ...
        cross(...
        laser_direction, ...
        referenceVector);

    e1 = ...
        e1 ./ ...
        max(norm(e1), 1e-12);

    e2 = ...
        cross(...
        laser_direction, ...
        e1);

    e2 = ...
        e2 ./ ...
        max(norm(e2), 1e-12);

    %% PROJECT POINTS INTO LASER BEAM PLANE

    X = ...
        relative * e1;

    Y = ...
        relative * e2;

    r2 = ...
        X.^2 + ...
        Y.^2;

    %% GAUSSIAN LASER INTENSITY

    I = ...
        (2 .* I0 ./ ...
        (pi .* w.^2)) .* ...
        exp(...
        -2 .* r2 ./ w.^2);

    %% ABSORBED HEAT FLUX

    q = ...
        absorptivity .* I;

    q = ...
        reshape(q, size(location.x));

end

 
% ROTATIONAL CONVECTION COEFFICIENT
 
function h = convectionCoefficientRotation(...
    location, ...
    omega_z, ...
    box_centroid, ...
    air_density, ...
    air_viscosity, ...
    air_conductivity, ...
    air_prandtl, ...
    L_characteristic, ...
    h_free)

    % POSITION
    x = location.x;
    y = location.y;

    % RADIAL DISTANCE FROM ROTATION AXIS
    r = sqrt(...
        (x - box_centroid(1)).^2 + ...
        (y - box_centroid(2)).^2);

    % ROTATIONAL VELOCITY
    velocity = abs(omega_z) .* r;

    % REYNOLDS NUMBER
    Re = air_density .* velocity .* ...
        L_characteristic ./ air_viscosity;
    Re = max(Re, 1);

    % NUSSELT NUMBER
    Nu = 0.664 .* sqrt(Re) .* ...
        air_prandtl.^(1/3);

    % TURBULENT REGION
    turbulent = Re >= 5e5;
    Nu(turbulent) = ...
        (0.037 .* Re(turbulent).^0.8 - 871) .* ...
        air_prandtl.^(1/3);

    % FORCED CONVECTION
    h_forced = ...
        Nu .* air_conductivity ./ L_characteristic;

    % TOTAL CONVECTION
    h = h_free + h_forced;
    h = max(h, 1e-6);

end

 
% INTERPOLATE PREVIOUS TEMPERATURE FIELD
 

function T_initial = ...
    interpolatePreviousTemperature(...
    location, ...
    previousNodes, ...
    previousTemperature)

    previousNodes = ...
        previousNodes';

    xq = ...
        location.x(:);

    yq = ...
        location.y(:);

    zq = ...
        location.z(:);

    F = ...
        scatteredInterpolant(...
        previousNodes(:,1), ...
        previousNodes(:,2), ...
        previousNodes(:,3), ...
        previousTemperature(:), ...
        "linear", ...
        "nearest");

    T_initial = ...
        F(...
        xq, ...
        yq, ...
        zq);

    T_initial = ...
        reshape(...
        T_initial, ...
        size(location.x));

end
